# Generated by Django 5.2.17 on 2026-08-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=120, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'FERIA_Modulo',
                'ordering': ['stand__orden', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stand',
                'verbose_name_plural': 'Stands',
                'db_table': 'FERIA_Stand',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=120, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('puntaje_minimo', models.PositiveSmallIntegerField(default=80)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='feria.modulo')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'FERIA_Evaluacion',
                'ordering': ['modulo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=120, unique=True)),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('MULTIPLE_CHOICE', 'Selección múltiple'), ('TRUE_FALSE', 'Verdadero / Falso'), ('SITUATIONAL', 'Situacional')], default='MULTIPLE_CHOICE', max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='feria.evaluacion')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'FERIA_Pregunta',
                'ordering': ['evaluacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('texto', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='feria.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Pregunta',
                'verbose_name_plural': 'Opciones de Pregunta',
                'db_table': 'FERIA_OpcionPregunta',
                'ordering': ['pregunta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='IntentoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('numero_intento', models.PositiveIntegerField()),
                ('es_correcta', models.BooleanField(db_index=True, default=False)),
                ('fecha_hora_respuesta', models.DateTimeField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_respuesta', to='participantes.sesionferia')),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='feria.opcionpregunta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='feria.pregunta')),
            ],
            options={
                'verbose_name': 'Intento de Respuesta',
                'verbose_name_plural': 'Intentos de Respuesta',
                'db_table': 'FERIA_IntentoRespuesta',
                'ordering': ['sesion', 'pregunta', 'numero_intento'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progresos', to='feria.modulo')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_modulo', to='participantes.sesionferia')),
            ],
            options={
                'verbose_name': 'Progreso de Módulo',
                'verbose_name_plural': 'Progresos de Módulo',
                'db_table': 'FERIA_ProgresoModulo',
            },
        ),
        migrations.AddField(
            model_name='modulo',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modulos', to='feria.stand'),
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=120, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insignias', to='feria.stand')),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
                'db_table': 'FERIA_Insignia',
                'ordering': ['stand__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InsigniaGanada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_obtencion', models.DateTimeField()),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otorgamientos', to='feria.insignia')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias_ganadas', to='participantes.sesionferia')),
            ],
            options={
                'verbose_name': 'Insignia Ganada',
                'verbose_name_plural': 'Insignias Ganadas',
                'db_table': 'FERIA_InsigniaGanada',
                'ordering': ['fecha_hora_obtencion'],
                'constraints': [models.UniqueConstraint(fields=('sesion', 'insignia'), name='uq_insignia_sesion')],
            },
        ),
        migrations.CreateModel(
            name='IntentoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actividad', models.CharField(db_index=True, max_length=150)),
                ('numero_intento', models.PositiveIntegerField()),
                ('respuesta_json', models.JSONField(blank=True, null=True)),
                ('es_correcta', models.BooleanField(db_index=True, default=False)),
                ('fecha_hora', models.DateTimeField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_actividad', to='participantes.sesionferia')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos_actividad', to='feria.modulo')),
            ],
            options={
                'verbose_name': 'Intento de Actividad',
                'verbose_name_plural': 'Intentos de Actividad',
                'db_table': 'FERIA_IntentoActividad',
                'ordering': ['sesion', 'modulo', 'codigo_actividad', 'numero_intento'],
                'indexes': [models.Index(fields=['sesion', 'modulo', 'codigo_actividad'], name='idx_intento_actividad')],
                'constraints': [models.UniqueConstraint(fields=('sesion', 'modulo', 'codigo_actividad', 'numero_intento'), name='uq_intento_actividad_num')],
            },
        ),
        migrations.AddConstraint(
            model_name='pregunta',
            constraint=models.UniqueConstraint(fields=('evaluacion', 'orden'), name='uq_pregunta_evaluacion_orden'),
        ),
        migrations.AddConstraint(
            model_name='opcionpregunta',
            constraint=models.UniqueConstraint(fields=('pregunta', 'codigo'), name='uq_opcion_pregunta_codigo'),
        ),
        migrations.AddConstraint(
            model_name='opcionpregunta',
            constraint=models.UniqueConstraint(fields=('pregunta', 'orden'), name='uq_opcion_pregunta_orden'),
        ),
        migrations.AddIndex(
            model_name='intentorespuesta',
            index=models.Index(fields=['sesion', 'pregunta'], name='idx_intento_sesion_pregunta'),
        ),
        migrations.AddConstraint(
            model_name='intentorespuesta',
            constraint=models.UniqueConstraint(fields=('sesion', 'pregunta', 'numero_intento'), name='uq_intento_sesion_pregunta_num'),
        ),
        migrations.AddIndex(
            model_name='progresomodulo',
            index=models.Index(fields=['sesion', 'estado'], name='idx_progreso_sesion_estado'),
        ),
        migrations.AddConstraint(
            model_name='progresomodulo',
            constraint=models.UniqueConstraint(fields=('sesion', 'modulo'), name='uq_progreso_sesion_modulo'),
        ),
        migrations.AddConstraint(
            model_name='modulo',
            constraint=models.UniqueConstraint(fields=('stand', 'orden'), name='uq_modulo_stand_orden'),
        ),
    ]
