# Generated by Django 5.2.17 on 2026-08-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'FERIA_Usuario',
                'ordering': ['cedula'],
            },
        ),
        migrations.CreateModel(
            name='SesionFeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('FINALIZADA', 'Finalizada')], db_index=True, default='EN_PROGRESO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='participantes.usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Feria',
                'verbose_name_plural': 'Sesiones de Feria',
                'db_table': 'FERIA_SesionFeria',
                'ordering': ['-fecha_hora_inicio'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='idx_sesion_usuario_estado'), models.Index(fields=['fecha_hora_inicio'], name='idx_sesion_fecha_inicio')],
            },
        ),
    ]
